### ISSUE TITLE
Any plans to add alternative Bearer authentication using personal access tokens?

### ISSUE THREAD

**Issue by moxue1989** [lvermeulen/Bitbucket.Net#12]
Loving this library, made integrating into our bit bucket server much easier. Better than Atlassian Stash.

Would like to suggest having the ability to Authenticate with Bearer tokens though.
This seems more secure than authenticating with username and password. And does not seem hard to implement. 

Using WithOAuthBearerToken instead of WithBasicAuth in GetBaseUrl.

Thanks!

**Comment by lvermeulen** [comment]
Thank you for the kind words!

Added in release [2.1.7](https://github.com/lvermeulen/Bitbucket.Net/releases/tag/2.1.7)
