### ISSUE TITLE
Multi-authentication clients

### ISSUE THREAD

**Issue by object71** [lvermeulen/Bitbucket.Net#13]
As it uses Flurl the authentication is actually cached per host for at least the first request. What this means is that if I use one bitbucket client and then create a second one with other credentials it would actually use the credentials from the first one.

To be resolved I think that instead of invoking requests directly agains the string using the flurl extensions a flurl client should be used and the bitbucket client should implement IDisposable.

**Comment by lvermeulen** [comment]
I would love to review the PR!
