### ISSUE TITLE
include pullrequest service

### ISSUE THREAD

**Issue by jmecosta** [lvermeulen/Bitbucket.Net#2]
hi,

would be great if https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/pullrequests would be included in this library

thanks

**Comment by lvermeulen** [comment]
Actually this library - for Bitbucket **SERVER** - has full support for pull requests. 

You're probably thinking of another project of mine, [Bitbucket.Cloud.Net](https://github.com/lvermeulen/Bitbucket.Cloud.Net). That one is a work in progress and is pretty low on my list of priorities right now. I do accept PR's though. :-)

**Comment by jmecosta** [comment]
Ok then i was not able to find either test or source code on how to create comments on pull request. Can you point out where can i find that. Thanks

**Comment by lvermeulen** [comment]
I apparently forgot to cover that one! I added it and it's in release [2.1.2](https://github.com/lvermeulen/Bitbucket.Net/releases/tag/2.1.2) - look for CreatePullRequestCommentAsync()

**Comment by jmecosta** [comment]
Thanks for the quick implementation
