### ISSUE TITLE
Incorrect JSON Format When Adding Comments to PRs

### ISSUE THREAD

**Issue by lrv1668** [lvermeulen/Bitbucket.Net#21]
When adding comments to a PR, [this API call](https://docs.atlassian.com/bitbucket-server/rest/7.7.1/bitbucket-rest.html#idp324) expects an `achor` key. This allows the comment to be applied to a line of a file in a diff. 

As far as I can tell, `CreatePullRequestCommentAsync` doesn't format the JSON data with the `anchor` key, meaning that comments only get applied at the overview level.

**Comment by lvermeulen** [comment]
Thanks for the PR, @lrv1668 !
