### ISSUE TITLE
Get Commit Properties in GetCommitAsync 

### ISSUE THREAD

**Issue by jmecosta** [lvermeulen/Bitbucket.Net#3]
hi,

would be great if the endpoint could already provide properties, we have this rest answer:
    "properties": {
        "jira-key": [
            "ticket"
        ]
    }

But the properties are missing from the Commit.

I can get the data from the comment, but then i need to run some regx to get the tickets. Would be nice to get directly the data from the endpoint.

thanks

**Comment by lvermeulen** [comment]
I'm not sure what you're talking about - which properties? If anything is missing from the library, I will happily review your pull request.

**Comment by jmecosta** [comment]
did try initially to do it, but was taking more than 5 min :) so open the ticket instead. anyway i try to do it if having a bit more time
