### ISSUE TITLE
please provide a signed nuget package on top of current unsigned

### ISSUE THREAD

**Issue by jmecosta** [lvermeulen/Bitbucket.Net#4]
hi
in our context we need a signed dll, could you provide one?
thanks

**Comment by lvermeulen** [comment]
I won't be providing a signed package (since I would need to put the private key in the repo, which kind of defeats the purpose), but you can do this yourself with the package [StrongNameSigner](https://www.nuget.org/packages/Brutal.Dev.StrongNameSigner).

**Comment by lvermeulen** [comment]
I finally bit the bullet and am providing a signed assembly starting from release 2.1.9.

**Comment by jmecosta** [comment]
Wow thanks, what made you change your mind? Maybe i can use the same
argument to convince other people 😉

**Comment by lvermeulen** [comment]
The arguments from the .NET Core team that signing is for identity, not security. And seeing that libraries such as MediatR and AutoMapper have been doing this for a while. And seeing that this wasn't all that much of a big deal for me to do. :-)

**Comment by jmecosta** [comment]
All good reasons indeed 🙂 thanks again
