### ISSUE TITLE
Determine conflict-status of a PR

### ISSUE THREAD

**Issue by fgather** [lvermeulen/Bitbucket.Net#5]
Hi, thanks for the great library!

According to https://community.atlassian.com/t5/Bitbucket-questions/REST-API-how-to-check-if-a-PR-has-conflict-s/qaq-p/716529
there is a really helpful api endpoint to determine the mergeability of a pull request:
https://bitbucket.org/api/1.0/repositories/<org_or_profile>/<repo_name>/pullrequests/<pull_request_id>/conflict-status

Do you have any plans on integrating that? 

Thanks in advance!

**Comment by lvermeulen** [comment]
That's a Bitbucket Cloud endpoint. :-)

You can check the mergeability of a pull request with the GetPullRequestMergeStateAsync() method. Hope that helps.
