### ISSUE TITLE
Deletion of Branches fails with 415

### ISSUE THREAD

**Issue by fgather** [lvermeulen/Bitbucket.Net#6]
Hi,

I stumbled upon a problem when deleting branches using DeleteRepoBranchAsync:

Unhandled Exception: System.AggregateException: One or more errors occurred. (DELETE https://*bitbucketserver*/rest/branch-utils/1.0/projects/*proj*/repos/*repo*/branches failed with status code 415 ().) ---> Flurl.Http.FlurlHttpException: DELETE https://*bitbucketserver*/rest/branch-utils/1.0/projects/*proj*/repos/*repo*/branches  failed with status code
 415 ().

Any idea why this blows up? I've got no fancy characters in the branch name and according to https://docs.atlassian.com/bitbucket-server/rest/5.9.0/bitbucket-rest.html
everything should be fine :(

Thx in advance!

**Comment by lvermeulen** [comment]
That's an invalid media type error, fixed in release fixed in release [2.1.3](https://github.com/lvermeulen/Bitbucket.Net/releases/tag/2.1.3)

**Comment by fgather** [comment]
Wow, that was quick, thx for the fast fix!

**Comment by lvermeulen** [comment]
No problem. :-)
