### ISSUE TITLE
DeclinePullRequest is throwing 405 error

### ISSUE THREAD

**Issue by nikitha789** [lvermeulen/Bitbucket.Net#7]
While using DeclinePullrequest Method,it is failing with status code 405. 

`FlurlHttpException: DELETE http://bitbucket.org/rest/api/1.0/projects/{projectkey}/repos/{slug}/pull-requests/1898/decline?version=2 failed with status code 405 ().
`

This is the method I have defined using the bitbucket package

`public bool DeclineUnapprovedBuildMasterPullRequests()
        {
            var openBuildMasterUnapprovedPullRequests = GetOpenBuildMasterPullRequests().Where(pr=> pr.Reviewers.Count(rev => rev.Approved) <PULL_APPROVAL_THRESHOLD).ToList();

            if (openBuildMasterUnapprovedPullRequests.Count > 0)
            {
                foreach (var pullRequest in openBuildMasterUnapprovedPullRequests)
                {
                    
                    var declinePullRequest = bitbucketClient.DeclinePullRequestAsync(settings.ProjectKey, settings.RepositorySlug, pullRequest.Id, pullRequest.Version).Result;
                    if (!declinePullRequest)
                        return false;
                }
            }

            return true;
        }
`

**Comment by lvermeulen** [comment]
I'm using the wrong verb there, fixed in release [2.1.3](https://github.com/lvermeulen/Bitbucket.Net/releases/tag/2.1.3)
