### ISSUE TITLE
Merging leads to 415 error

### ISSUE THREAD

**Issue by fgather** [lvermeulen/Bitbucket.Net#8]
Hi,

since the last release I get an 415 return code when I try to execute a merge:

POST https://bitbucket.*****.com/rest/api/1.0/projects/TM/repos/tm5/pull-requests/486/merge?version=11 failed with status code 415 

Any idea what the reason might be? The previous release worked fine for me.

**Comment by lvermeulen** [comment]
Can you try prerelease [2.1.4-alpha](https://github.com/lvermeulen/Bitbucket.Net/releases/tag/2.1.4-alpha)?

**Comment by fgather** [comment]
Looks good! Thank you for the fast response!

**Comment by lvermeulen** [comment]
The actual release is 2.1.5
