### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by iannewson** [lvermeulen/Bitbucket.Net#9]
Hi,

This project needs some documentation. It's not clear how to use the API.

It's also not clear if this works with Bitbucket cloud.

**Comment by rogerfar** [comment]
Please write some docs.

**Comment by lvermeulen** [comment]
There you go: https://developer.atlassian.com/server/bitbucket/reference/rest-api/

The Bitbucket Cloud project is here: https://github.com/lvermeulen/Bitbucket.Cloud.Net

**Comment by monodop** [comment]
Bitbucket documentation does not count. How do I use **this** library? Is it even meant for public usage?

**Comment by benlabbeus** [comment]
Are you going to document this? How to connect to bit bucket? And use some basic commands?
